# Node.js
# Build a general Node.js project with npm.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

trigger:
- master

pool:
  vmImage: 'Ubuntu-16.04'

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '10.x'
  displayName: 'Install Node.js'

- script: |
    npm install
  displayName: 'npm install and build'

- script: |
    gulp clean
    gulp bundle --ship
    gulp package-solution --ship
  displayName: 'Build and package the solution'

#- task: PublishBuildArtifacts@1
#  inputs:
#    PathtoPublish: '$(Build.SourcesDirectory)/sharepoint/solution/quicklinks.sppkg'
#    artifactName: 'SPFx sppkg'
#  displayName: 'Publish build SPFx artifacts'

#- task: PublishBuildArtifacts@1
#  inputs:
#    PathtoPublish: '$(Build.SourcesDirectory)/devops/release/'
#    artifactName: 'Office 365 CLI scripts'
#  displayName: 'Publish build office 365 artifacts'